### ISSUE TITLE
递交申请

### ISSUE THREAD

**Issue by wangjinang** [Fuukei/Sakurairo_Wiki#7]
"name": "Wang Jin ang Blog", 
"url": "https://www.wangjinang.cn", 
"avatar": "https://www.wangjinang.cn/wp-content/uploads/2021/07/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20210727190745.jpg", 
"desc": "本当の声を響かせてよ"

**Comment by beixibaobao** [comment]
> "name": "Wang Jin ang Blog",
> "url": "https://www.wangjinang.cn",
> "avatar": "https://www.wangjinang.cn/wp-content/uploads/2021/07/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20210727190745.jpg",
> "desc": "本当の声を響かせてよ"

经过测试，海外访问并未获得正常的301http到https跳转 或者是 200OK的返回，无法通过申请。
